# =========================================================
# DEVELOPMENT PROFILE
# =========================================================

server.port=8080

# =========================================================
# MYSQL
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/academy_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# MAIL
# =========================================================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
spring.mail.username=db6f7d7123dc4b
spring.mail.password=3a7f8887a1fabc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Academy contact
academy.contact.email=kwivrainnovations@gmail.com

# =========================================================
# JWT
# =========================================================

app.jwt.secret=academy-api-jwt-secret-key-2026-this-must-be-long-enough
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================================================
# CORS
# =========================================================

app.cors.allowed-origins=http://localhost:3000

# =========================================================
# LOGGING
# =========================================================

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE